In [2]:
def product(nums):
    total = 1
    for i in nums:
        total *= i
    return total

res1 = (lambda **kwargs: product(kwargs.values()))
res1(a = 10, b = 20, c = 30), res1(a = 10, b = 20, c = 30, d = 40, e = 50)

(6000, 12000000)

In [3]:
list1 = [1,2,3,4,5,6,7,8,9]

def odd(n):
    if n%2 == 1:
        return True
    else:
        return False
    
odd_num = list(filter(odd, list1))
odd_num

[1, 3, 5, 7, 9]

In [4]:
def twice(n):
    return n*2

doubles = list(map(twice, odd_num))
doubles

[2, 6, 10, 14, 18]

In [5]:
doubles = list(map(lambda n:n*2 , odd_num))

In [6]:
doubles

[2, 6, 10, 14, 18]

In [7]:
from functools import reduce

In [8]:
def add(a, b):
    return a + b

sum_all = reduce(add, doubles)
sum_all

50

In [9]:
sum_all = reduce(lambda a, b : a + b, doubles)
sum_all

50

In [12]:
sum_all = reduce(lambda a, b : a + b,list(map(lambda n:n*2,list(filter(lambda n:n%2 == 1, list1)))))
sum_all                                       

50

In [13]:
mysum = reduce(lambda a, b : a + b,list(map(lambda n:n*2,list(filter(lambda n:n%2 == 1, list1)))))
mysum

50

In [14]:
from numpy import *
import time

def trad_version():
    t1 = time.time()
    X = range(10000000)
    Y = range(10000000)
    Z = []
    for i in range(len(X)):
        Z.append(X[i] + Y[i])
    return time.time() - t1

trad_version()

4.81363844871521

In [15]:
def numpy_version():
    t1 = time.time()
    X = arange(10000000)
    Y = arange(10000000)
    Z = X + Y
    return time.time() - t1

numpy_version()

0.05385851860046387

In [16]:
import numpy as np
import warnings
warnings.filterwarnings("ignore")

In [17]:
list1 = [10,20,30,40,50,60]
list1

[10, 20, 30, 40, 50, 60]

In [18]:
type(list1)

list

In [19]:
arr1 = np.array(list1)
arr1

array([10, 20, 30, 40, 50, 60])

In [20]:
type(arr1)

numpy.ndarray

In [21]:
arr1.data

In [22]:
arr1.dtype

dtype('int32')

In [23]:
arr1.astype(float)

array([10., 20., 30., 40., 50., 60.])

In [24]:
np.arange(0, 10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [25]:
np.arange(0, 100, 10)

array([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

In [26]:
np.arange(100, 10, -10)

array([100,  90,  80,  70,  60,  50,  40,  30,  20])

In [27]:
arr3 = np.arange(0, 10)
arr3.shape

(10,)

In [28]:
arr3.size

10

In [29]:
arr3.itemsize

4

In [30]:
arr3.dtype

dtype('int32')

In [31]:
arr3.nbytes

40

In [32]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [33]:
np.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [34]:
np.repeat(10, 5)

array([10, 10, 10, 10, 10])

In [40]:
a = np.array([10,20,30])
np.repeat(a, 3)

array([10, 10, 10, 20, 20, 20, 30, 30, 30])

In [41]:
np.full(5, 10)

array([10, 10, 10, 10, 10])

In [42]:
ar1 = np.arange(1, 20)
ar1[ar1 % 2 == 1]

array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19])

In [46]:
ar1 = np.arange(1, 20)
ar1[ar1 % 2 == 0]

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18])

In [47]:
np.linspace(10, 20, 4)

array([10.        , 13.33333333, 16.66666667, 20.        ])

In [48]:
np.linspace(10, 20, 11)

array([10., 11., 12., 13., 14., 15., 16., 17., 18., 19., 20.])

In [49]:
np.random.random(4)

array([0.02406279, 0.85121   , 0.39860719, 0.54715214])

In [50]:
np.random.randint(0, 500, 5)

array([ 38, 137,  88, 101, 432])

In [51]:
np.random.seed(123)
np.random.randint(0, 100, 10)

array([66, 92, 98, 17, 83, 57, 86, 97, 96, 47])

In [52]:
np.random.seed(101)
np.random.randint(0, 100, 10)

array([95, 11, 81, 70, 63, 87, 75,  9, 77, 40])

In [53]:
np.random.seed(101)
np.random.randint(0, 100, 10)

array([95, 11, 81, 70, 63, 87, 75,  9, 77, 40])

In [54]:
f1 = np.random.uniform(5, 10, size = (10))
f1

array([6.5348311 , 9.4680654 , 8.60771931, 5.94969477, 7.77113796,
       6.76065977, 5.90946201, 8.92800881, 9.82741611, 6.16176831])

In [55]:
np.floor(f1)

array([6., 9., 8., 5., 7., 6., 5., 8., 9., 6.])

In [56]:
f1.astype(int)

array([6, 9, 8, 5, 7, 6, 5, 8, 9, 6])

In [57]:
b2 = np.random.randn(10)
b2

array([ 0.18869531, -0.75887206, -0.93323722,  0.95505651,  0.19079432,
        1.97875732,  2.60596728,  0.68350889,  0.30266545,  1.69372293])

In [58]:
arr1

array([10, 20, 30, 40, 50, 60])

In [60]:
for index, value in np.ndenumerate(arr1):
    print(index, value)

(0,) 10
(1,) 20
(2,) 30
(3,) 40
(4,) 50
(5,) 60


In [61]:
arr2 = np.arange(1, 20)
arr2

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19])

In [62]:
arr2.sum()

190

In [63]:
np.cumsum(arr2)

array([  1,   3,   6,  10,  15,  21,  28,  36,  45,  55,  66,  78,  91,
       105, 120, 136, 153, 171, 190], dtype=int32)

In [ ]:
 #min(), max(), argmin(), argmax(), mean(), median(), var()

In [64]:
np.std(arr2)

5.477225575051661

In [66]:
A = np.array([[1,2,3,0], [5,6,7,22], [10,11,1,13], [14,15,16,3]])
A

array([[ 1,  2,  3,  0],
       [ 5,  6,  7, 22],
       [10, 11,  1, 13],
       [14, 15, 16,  3]])

In [67]:
A.sum()

129

In [68]:
A.min()

0

In [69]:
A.max()

22

In [70]:
np.amin(A, axis = 0)

array([1, 2, 1, 0])

In [71]:
np.amin(A, axis = 1)

array([0, 5, 1, 3])

In [72]:
#mean(), median() ,var(), std()

In [73]:
for index, value in np.ndenumerate(A):
    print(index, value)

(0, 0) 1
(0, 1) 2
(0, 2) 3
(0, 3) 0
(1, 0) 5
(1, 1) 6
(1, 2) 7
(1, 3) 22
(2, 0) 10
(2, 1) 11
(2, 2) 1
(2, 3) 13
(3, 0) 14
(3, 1) 15
(3, 2) 16
(3, 3) 3


In [74]:
a = np.array([7,5,3,9,0,2])
a[0]

7

In [75]:
a[1:]

array([5, 3, 9, 0, 2])

In [76]:
a[1:4]

array([5, 3, 9])

In [77]:
a[-1]

2

In [78]:
a[-3:-1]

array([9, 0])

In [79]:
ar = np.arange(1, 20)
ar

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19])

In [80]:
rep1 = np.where(ar % 2 == 0, 0, ar)
print(rep1)

[ 1  0  3  0  5  0  7  0  9  0 11  0 13  0 15  0 17  0 19]


In [81]:
ar2 = np.array([10, 20, 30, 10, 10, 20, 20])
ar2

array([10, 20, 30, 10, 10, 20, 20])

In [82]:
rep2 = np.where(ar2 == 10, 99, ar2)
print(rep2)

[99 20 30 99 99 20 20]


In [83]:
p2 = np.arange(0, 100, 10)
p2

array([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

In [84]:
np.put(p2, [0, 3, 5], [33, 55, 99])
p2

array([33, 10, 20, 55, 40, 99, 60, 70, 80, 90])

In [85]:
a = np.array([10, np.nan, 20, 30, 60, np.nan, 90, np.inf])
a

array([10., nan, 20., 30., 60., nan, 90., inf])

In [86]:
np.isnan(a)

array([False,  True, False, False, False,  True, False, False])

In [87]:
np.where(np.isnan(a))

(array([1, 5], dtype=int64),)

In [88]:
a[np.isnan(a)] = 99
a

array([10., 99., 20., 30., 60., 99., 90., inf])

In [89]:
np.isnan(a).any()

False

In [90]:
A = np.array([[1,2,np.nan,4], [np.nan, 6,7,8], [10,np.nan,12,13], [14,15,16,17]])
A

array([[ 1.,  2., nan,  4.],
       [nan,  6.,  7.,  8.],
       [10., nan, 12., 13.],
       [14., 15., 16., 17.]])

In [91]:
np.isnan(A)

array([[False, False,  True, False],
       [ True, False, False, False],
       [False,  True, False, False],
       [False, False, False, False]])

In [92]:
np.where(np.isnan(A))

(array([0, 1, 2], dtype=int64), array([2, 0, 1], dtype=int64))